version: '3'

services:
  utils:
    build: .
    command: poetry run pytest tests/
    depends_on:
      - pushgateway
    volumes:
      - .:/app/
    environment:
      PUSHGATEWAY_URL: http://pushgateway:9091
  pushgateway:
    image: weaveworks/prom-aggregation-gateway
    command: --web.enable-admin-api
    ports:
      - "9091:9091"
      