version: '3'

services:
  utils:
    build: .
    command: poetry run pytest tests/
    depends_on:
      - pushgateway
    volumes:
      - .:/app/
    environment:
      # The hostname is used to generate the experiment ID.
      # Docker will give an incompatable hostname. Possibly revisit this later.
      HOSTNAME: 'test-server.lan'
      PUSHGATEWAY_URL: http://pushgateway:9091
  pushgateway:
    image: prom/pushgateway:v1.3.0
    command: --web.enable-admin-api
    ports:
      - "9091:9091"
      