version: '3'

services:
  utils:
    build: .
    command: poetry run pytest tests/
    depends_on:
      - pushgateway
    # Similar to the original, just doesnt volume in files because
    # CircleCI doesnt like volume inception
    # https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
    environment:
      HOSTNAME: 'test-server.lan'
      PAPERSPACE_METRIC_PUSHGATEWAY: http://pushgateway:9091
  pushgateway:
    image: prom/pushgateway:v1.3.0
    command: --web.enable-admin-api
    ports:
      - "9091:9091"
      