version: 2.1

executors:
  python-tox:
    docker:
      - image: themattrix/tox-base:latest

jobs:
  test:
    executor: python-tox
    steps:
      - checkout
      - run:
          name: Run tests
          command: make run-tests
  build:
    executor: python-tox
    steps:
      - checkout
      - run:
          name: Install package requirements
          command: make pip-install-dev
      - run:
          name: Build Gradient SDK package
          command: make build
      - run:
          name: List all elements in current location
          command: ls -al

workflows:
  version: 2.1
  pipeline:
    jobs:
      - test
      - build:
          filters:
            tags:
              only: /^v.*/
          requires:
              - test
