version: 2.1

commands:
  test:
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: make dc-setup
      - run: make dc-test

jobs:
  build-python27:
    docker:
      - image: circleci/python:2.7
    steps:
      - test
  build-python35:
    docker:
      - image: circleci/python:3.5
    steps:
      - test
  build-python36:
    docker:
      - image: circleci/python:3.6
    steps:
      - test
  build-python37:
    docker:
      - image: circleci/python:3.7
    steps:
      - test
  build-python38:
    docker:
      - image: circleci/python:3.8
    steps:
      - test
  build-python39:
    docker:
      - image: circleci/python:3.9
    steps:
      - test
  # test:
  #   executor: python-tox
  #   steps:
  #     - checkout
  #     - run:
  #         name: Run tests
  #         command: make run-tests
  #     - run:
  #         name: Get latest version from tags
  #         command: echo export sdk_version="$(git describe --tags --abbrev=0 | sed -r 's/.*(([0-9]+\.){2}([0-9]+))/\1/')" >> $BASH_ENV
  #     - run:
  #         name: Install package requirements
  #         command: make pip-install-dev
  #     - run:
  #         name: Set correct version for build
  #         command: sed -i "s/0.0.1/$sdk_version/" gradient_utils/__init__.py
  #     - run:
  #         name: Build Gradient SDK package
  #         command: make build
  # publish:
  #   executor: python-tox
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install requirements to publish package
  #         command: make pip-install-dev
  #     - run:
  #         name: Get latest version from tags
  #         command: echo export sdk_version="$(git describe --tags --abbrev=0 | sed -r 's/.*(([0-9]+\.){2}([0-9]+))/\1/')" >> $BASH_ENV
  #     - run:
  #         name: Set correct version for build
  #         command: sed -i "s/0.0.1/$sdk_version/" gradient_utils/__init__.py
  #     - run:
  #         name: Publish package
  #         command: make publish

workflows:
  version: 2.1
  pipeline:
    jobs:
      - build-python27
      - build-python35
      - build-python36
      - build-python37
      - build-python38
      - build-python39
      # - test:
      #     filters:
      #       tags:
      #         only: /^v.*/
      # - hold:
      #     type: approval
      #     requires:
      #       - test
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
      # - publish:
      #     requires:
      #       - hold
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
