version: 2.1

executors:
  python-tox:
    docker:
      - image: themattrix/tox-base:latest

jobs:
  test:
    executor: python-tox
    steps:
      - run: make run-tests

workflows:
  version: 2.1
  pipeline:
    jobs:
      - test
