version: 2.1

executors:
  python-tox:
    docker:
      - image: themattrix/tox-base:latest

jobs:
  test:
    executor: python-tox
    steps:
      - run:
          name: Check path where we are
          command: pwd
      - run:
          name: List elements in current folder
          command: ls -al
#      - run:
#          name: Run docker image with tests
#          command: docker run -it -v ..:/gradient-sdk -w /gradient-sdk themattrix/tox-base make run-tests

workflows:
  version: 2.1
  pipeline:
    jobs:
      - test
