version: 2.1

executors:
  python-tox:
    docker:
      - image: themattrix/tox-base:latest

jobs:
  test:
    executor: python-tox
    steps:
      - run:
          name: List available containers
          command: docker  ps -a
      - run:
          name: Run docker image with tests
          command: docker run -it -v ..:/gradient-sdk -w /gradient-sdk themattrix/tox-base make run-tests

workflows:
  version: 2.1
  pipeline:
    jobs:
      - test
