version: 2.1

commands:
  test:
    parameters:
      version:
        default: "3.9"
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: sed -i 's/_version_/<<parameters.version>>/' Dockerfile.ci && mv Dockerfile.ci Dockerfile
      - run: make dc-setup
      - run: make dc-test

jobs:
  build-python35:
    docker:
      - image: cimg/base:stable
    steps:
      - test:
          version: "3.5"
  build-python36:
    docker:
      - image: cimg/base:stable
    steps:
      - test:
          version: "3.6"
  build-python37:
    docker:
      - image: cimg/base:stable
    steps:
      - test:
          version: "3.7"
  build-python38:
    docker:
      - image: cimg/base:stable
    steps:
      - test:
          version: "3.8"
  build-python39:
    docker:
      - image: cimg/base:stable
    steps:
      - test:
          version: "3.9"
  build-publish:
    docker:
      - image: cimg/base:stable
    steps:
      - test:
          version: "3.9"
    steps:
      - checkout
      - setup_remote_docker:
        version: 19.03.13
      - run: sed -i 's/_version_/3.9/' Dockerfile.ci && mv Dockerfile.ci Dockerfile
      - run:
          name: Build Gradient SDK package and publish to PyPI
          command: make clean-build-publish

workflows:
  version: 2.1
  pipeline:
    jobs:
      - build-python36
      - build-python37
      - build-python38
      - build-python39
      - hold:
          type: approval
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-publish:
          requires:
            - hold
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
